<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_atendimentosebraego.com.br</name>
   <tag></tag>
   <elementGuidId>c4620e78-cdcc-4c9e-adb3-c08ba98a5c89</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emailft</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>atendimento@sebraego.com.br</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;webkit chrome win js webkit chrome win js js&quot;]/body[1]/div[1]/footer[1]/div[@class=&quot;centralFooter&quot;]/div[@class=&quot;centralrelacionamento&quot;]/p[@class=&quot;emailft&quot;]</value>
   </webElementProperties>
</WebElementEntity>
