<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_caret</name>
   <tag></tag>
   <elementGuidId>52908333-fac4-43d6-a943-f02d2963ecab</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contaUsuario&quot;)/div[@class=&quot;dropdown userlogged&quot;]/button[@class=&quot;btn btn-default dropdown-toggle btnLogado&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
</WebElementEntity>
